# Generated by Django 4.1.3 on 2022-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='caracteristica_empresa',
            new_name='caracteristica_empresapython',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('M', 'Mercado'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia'), ('A', 'Alimentação')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
