# Generated by Django 4.1.3 on 2022-11-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_tecnologias_empresa_logo_empresa_tecnologias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='caracteristica_empresapython',
            new_name='caracteristica_empresa',
        ),
    ]
